service:
  parsers_file: parsers.conf

config:
  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Parser docker
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off

  outputs: |
    [OUTPUT]
        Name cloudwatch_logs
        Match kube.*
        region ap-south-1
        log_group_name /aws/eks/demo-alb-logs
        log_stream_prefix from-fluent-bit-
        auto_create_group true